services:
  - type: web
    name: llistadelacompra
    runtime: node
    plan: starter
    region: frankfurt
    buildCommand: ""
    startCommand: node server.js
    healthCheckPath: /healthz
    envVars:
      - key: AUTH_USERS
        sync: false
